[project]
name = "sprint-the-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy>=2.2.1", "pyxel>=2.2.8", "ruff>=0.8.4"]
